import React from 'react';
import { useTranslation } from 'react-i18next';
import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';

const PrivacyPolicy: React.FC = () => {
  const { t } = useTranslation();
  return (
    <div className="items-center relative flex flex-col overflow-hidden bg-neutral-950 pt-[10px] min-h-screen">
      <Navigation />
      
      <main className="w-full flex flex-col items-center">
        <div className="max-w-4xl mx-auto px-4 md:px-6 pt-28 md:pt-36 pb-8 md:pb-12">
          <div className="text-white font-geist">
            {/* Header */}
            <div className="mb-12">
              <h1 className="text-4xl md:text-5xl font-bold mb-6">Calistant Privacy Policy</h1>
              <div className="text-neutral-400 text-lg">
                <p>Last revised: June 6, 2025</p>
                <p>Effective: June 6, 2025</p>
              </div>
            </div>

            {/* Introduction */}
            <section className="mb-12">
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                Hello! At Calistant, we believe that understanding your meals shouldn't feel like solving a math problem. We're here to help you build healthier habits by making meal tracking easy, smart, and even a little fun. We are not a medical or dietary service. Since this is a personal journey, we do collect some information to make your experience as helpful and personalized as possible.
              </p>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                This Privacy Policy ("Policy") outlines how Calistant handles your personal information during your use of the app. It explains what kind of data is collected, how it's used, and how your privacy is safeguarded. You'll also find information about your rights and the choices you have regarding your data. This Policy is closely linked to our Terms of Use, where additional details and definitions are available if you're curious to explore further.
              </p>
              <p className="text-neutral-300 text-lg leading-relaxed">
                Calistant is designed for individuals who are 18 years of age or older. If you are under 18, please do not create an account or use Calistant. Our systems are designed to restrict access for individuals below this age. If we discover that a user under the age of 18 has submitted personal information, we will promptly delete the data and close the account to protect their privacy.
              </p>
            </section>

            {/* Medical Disclaimer */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">Calistant is not a medical advice app</h2>
              <ul className="space-y-3 text-neutral-300 text-lg leading-relaxed ml-6 mb-6">
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Calistant is not a licensed healthcare provider or a substitute for medical advice.
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  All suggestions and insights are generated by AI and should be considered informational only.
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Users should consult a qualified doctor or dietitian before making any significant dietary changes.
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Calistant does not generate personalized diet plans or allergy-safe recommendations.
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  If you have any medical condition, food allergy, or dietary restriction, please consult a professional.
                </li>
              </ul>
              <p className="text-neutral-300 text-lg leading-relaxed">
                This app is not a diet generator. It is a supportive tool for food planning and awareness. Decisions based on app outputs are the responsibility of the user.
              </p>
            </section>

            {/* AI Limitations */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">AI Limitations</h2>
              <ul className="space-y-3 text-neutral-300 text-lg leading-relaxed ml-6">
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  The app uses AI algorithms that may produce inaccurate, incomplete, or misleading information.
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  The AI may misclassify foods or fail to detect allergens.
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  We cannot guarantee the nutritional accuracy of every food entry, barcode, or user-generated content.
                </li>
              </ul>
            </section>

            {/* Personal Information Collection */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">Personal Information We Collect</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-8">
                We may collect your personal information through three primary sources: directly from you, automatically as you interact with our Services, and from authorized third parties.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Personal Information We Collect Directly from You</h3>
              
              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Account and Profile Information</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  When you sign up for Calistant, you may provide details such as your name, email address, general location (such as country), profile image (if you choose to upload one), username, password, date of birth, and gender.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Food and Activity Diary Data</h4>
                <p className="text-neutral-300 text-lg leading-relaxed mb-4">
                  Calistant includes features that allow you to log meals, track your activity, and monitor your health goals. When using these features, you may voluntarily submit information such as:
                </p>
                <ul className="space-y-2 text-neutral-300 text-lg leading-relaxed ml-6 mb-4">
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Eating and nutrition habits
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Foods, beverages, and medications you consume (including those logged via voice input, text, or barcode scanning), and in the future, possibly groceries purchased via third-party integrations
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Calorie intake and nutrient breakdown
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Dietary preferences or restrictions
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Fitness activity, exercise routines, and related goals (e.g., "increase daily protein intake")
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Lifestyle habits such as sleep data
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Body-related metrics like height, weight, and BMI
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Information related to physical or health conditions
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Optional progress photos
                  </li>
                  <li className="flex items-start">
                    <span className="text-white mr-2">•</span>
                    Notes or reflections about your habits, physical condition, or mindset
                  </li>
                </ul>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  Some of this data may be considered sensitive personal information if it directly or indirectly indicates a medical or health condition.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Communications with Calistant</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  When you contact our team—for example, through customer support channels, feedback forms, or in-app messaging—we may collect your name, email address, and the content of those messages, including any responses you receive from us or from automated support features such as our chatbot.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Payment Information</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  If you purchase a Premium Subscription or any paid feature via Calistant's platform, your payment details (such as credit card number, billing address) may be processed by a third-party payment processor. Calistant itself does not store or access your full payment credentials but may retain transaction-related metadata (e.g., subscription tier, status, renewal dates) for account management and billing purposes.
                </p>
              </div>
            </section>

            {/* Automatically Collected Information */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">Automatically Collected Personal Information: Usage, Device Data & Cookies</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                Calistant may automatically collect certain information related to your device and how you interact with the Services. This includes technical details such as your browser type, operating system, device model, unique identifiers (e.g., IP address, mobile advertising ID, cookie ID), internet service provider, and mobile network operator. We may also collect general location data inferred from your IP address, as well as data on your in-app behavior—such as actions taken, time spent using different features, frequency of use, navigation paths, and clicks on specific links or elements within the app or website.
              </p>

              <h3 className="text-2xl font-semibold mb-4">What Are Cookies?</h3>
              <p className="text-neutral-300 text-lg leading-relaxed mb-4">
                Cookies are small data files stored on your device by your browser when you visit a website or use a web-based app. Like many digital platforms, Calistant and its authorized third-party partners may use various tracking technologies—including cookies, pixels, web beacons, SDKs, log files, and local storage mechanisms—to collect information for operational and analytical purposes.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Managing Your Cookie Preferences</h3>
              <p className="text-neutral-300 text-lg leading-relaxed">
                Your ability to manage cookies may vary depending on your location and applicable regulations. Most browsers allow you to modify your settings to accept all cookies, reject all cookies, or notify you each time a cookie is being placed on your device. Note that if you disable or reject cookies, certain features of Calistant's Services may no longer function as intended.
              </p>
            </section>

            {/* Third Party Information */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">Personal Information We Receive From Third Parties</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                Calistant may receive personal data about you from various external sources, including third-party health integrations, service providers, research collaborators, marketing and advertising partners, and social media platforms. This information is used to enhance the Services and offer a more personalized and secure experience.
              </p>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Service Providers</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  Authorized service providers may share information with Calistant as part of their role in supporting the functionality of the Services. For example, usage behavior and interaction patterns may be provided by analytics services to improve user experience, identify performance issues, or ensure system security.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Connected Health Devices</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  If Calistant is integrated with compatible connected devices—such as activity trackers, smart scales, heart rate monitors, glucose monitors, or other wearables—it may receive activity and biometric data with your explicit permission. This may include steps, heart rate, sleep data, weight, and workout sessions.
                </p>
              </div>
            </section>

            {/* How We Use Information */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">How We Use Your Personal Information</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-8">
                Calistant may use the personal information we collect for the purposes outlined below, or as otherwise clearly communicated at the time the data is collected. Please note that any activity-based data (such as logged meals, calories, or fitness routines) is used solely for delivering the core functionality of the Calistant platform and is never sold or disclosed to third parties outside of these service-related purposes.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Service Functionality and User Experience</h3>
              <p className="text-neutral-300 text-lg leading-relaxed mb-4">Personal information may be processed to:</p>
              <ul className="space-y-2 text-neutral-300 text-lg leading-relaxed ml-6 mb-6">
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Operate, maintain, and enhance the features and performance of the Calistant platform
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Create and manage your user profile and account
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Communicate essential service information, including app updates, notifications, account-related alerts, and administrative notices
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Customize your experience and content based on preferences, habits, and usage behavior
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Provide timely technical assistance, handle support requests, and address user inquiries or concerns
                </li>
              </ul>

              <h3 className="text-2xl font-semibold mb-4">Research and Product Development</h3>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                We may use collected information in support of product improvement, usability research, and service development. As part of this process, user data may be transformed into aggregated or anonymized forms—ensuring that no individual can be identified.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Legal Compliance and Security</h3>
              <p className="text-neutral-300 text-lg leading-relaxed mb-4">Calistant may also process personal information when necessary to:</p>
              <ul className="space-y-2 text-neutral-300 text-lg leading-relaxed ml-6">
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Meet legal obligations or respond to valid governmental or regulatory requests
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Protect the rights, safety, and property of users, Calistant personnel, or the general public
                </li>
                <li className="flex items-start">
                  <span className="text-white mr-2">•</span>
                  Detect, investigate, and respond to potential security breaches, fraudulent behavior, or unauthorized use
                </li>
              </ul>
            </section>

            {/* How We Share Information */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">How We Share Personal Information</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-8">
                Calistant may share personal data with specific categories of third parties, always in alignment with the purposes described in this Privacy Policy and applicable legal requirements.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Service Providers and Vendors</h3>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                We rely on trusted third-party vendors to support day-to-day operations and to help deliver Calistant's functionality. These service providers may include providers of hosting and cloud infrastructure, payment processors, customer service platforms, data analytics providers, and IT consultants. These entities only access your data for purposes directly tied to their services and are contractually bound to protect your information.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Legal and Regulatory Requirements</h3>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                Calistant may disclose personal information where required to comply with applicable laws, court orders, or legitimate requests from governmental and law enforcement authorities. This may also include disclosures for tax, audit, compliance, or public safety reasons.
              </p>

              <h3 className="text-2xl font-semibold mb-4">Business Transitions</h3>
              <p className="text-neutral-300 text-lg leading-relaxed">
                In the event of a potential merger, acquisition, financing, asset transfer, reorganization, or bankruptcy, personal data may be disclosed or transferred as part of due diligence or completion of the transaction.
              </p>
            </section>

            {/* Data Retention */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">How Calistant Retains Your Information</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                Calistant retains your personal information for as long as it is needed to support the purposes described in this Privacy Policy, including to comply with legal, regulatory, or reporting obligations. In some cases, applicable laws may require us to store certain data for a longer period, or allow us to retain it for archiving or business continuity purposes.
              </p>
              <p className="text-neutral-300 text-lg leading-relaxed">
                When determining how long to retain specific types of personal data, we consider several factors, including: the volume and sensitivity of the information, the potential risks associated with unauthorized access or disclosure, the reason the information was collected, whether the intended purpose can still be met, and any legal obligations or industry standards that apply.
              </p>
            </section>

            {/* Data Protection */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">How Calistant Protects Your Information</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                Calistant implements a combination of technical, organizational, and administrative measures to help safeguard your personal information from loss, misuse, unauthorized access, disclosure, alteration, or destruction. These safeguards are designed in accordance with industry best practices and are regularly reviewed to ensure ongoing data protection.
              </p>
              <p className="text-neutral-300 text-lg leading-relaxed">
                However, it is important to note that no system or method of electronic data storage or transmission over the internet can be guaranteed to be fully secure. While Calistant takes reasonable steps to protect your information, absolute security cannot be assured.
              </p>
            </section>

            {/* Privacy Rights */}
            <section className="mb-12">
              <h2 className="text-3xl font-bold mb-6">Your Privacy Rights</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-8">
                Depending on your place of residence, you may have specific legal rights regarding how your personal information is collected, used, stored, and shared. Calistant respects these rights and is committed to supporting individuals in exercising them in accordance with applicable laws.
              </p>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Right to Access and Data Portability</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  You may have the right to request confirmation about whether Calistant processes your personal information and to access or receive a copy of your data in a commonly used, portable format, when technically feasible.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Right to Deletion</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  You may request that we delete your personal data, subject to certain limitations permitted or required by law (such as compliance with legal obligations or security purposes).
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Right to Correction</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  If any personal information we hold is inaccurate or incomplete, you have the right to request that it be corrected, taking into account the nature of the data and the purposes for which it is processed.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Right to Non-Discrimination</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  Calistant will never deny access to our services, reduce functionality, or impose penalties if you choose to exercise your legal privacy rights.
                </p>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-3 text-neutral-200">Right to Appeal</h4>
                <p className="text-neutral-300 text-lg leading-relaxed">
                  If you submit a privacy-related request and disagree with our response, you may have the right to appeal. Appeals can be submitted by contacting us at <a href="mailto:privacy@calistant.com" className="text-blue-400 hover:text-blue-300 underline">privacy@calistant.com</a> with the subject line "APPEAL".
                </p>
              </div>
            </section>

            {/* Contact */}
            <section className="mb-12 border-t border-neutral-800 pt-8">
              <h2 className="text-3xl font-bold mb-6">Contact</h2>
              <p className="text-neutral-300 text-lg leading-relaxed mb-6">
                If you have any questions, concerns, or requests related to this Privacy Policy or Calistant's data practices, you can contact us at:
              </p>
              <p className="text-neutral-300 text-lg leading-relaxed">
                📧 <a href="mailto:privacy@calistant.com" className="text-blue-400 hover:text-blue-300 underline">privacy@calistant.com</a>
              </p>
            </section>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default PrivacyPolicy; 